pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./absencecreate.html","TeacherForm &#62; AbsenceCreate","Për të krijuar një mungesë të re, hapet forma:  ku shtyp n të dhënat: zgjedhet klasa, lënda,  ra mësimore (1-6), arsyeja e mungesës (e a...",""],
["./absencelist.html","TeacherForm &#62; AbsenceList","Në kftë pjesë shfaqet lista e mungesave me të dëënët përkatëse:",""],
["./adminform.html","AdminForm","Pasi të jepën të dhënat (usernaie dh  password) dhe të zgjhdhet gjuha (në këtë rast anglisht) hapet Menu e Administratës, ëëse përdoruesi ka ...",""],
["./classescreate.html","AdminForm &#62; ClassesCreate","Për të krijuar një klasë të re, hapet forma:  ku shtypen të dhënat: zgjedhet arsimtari i klasës (kujdestari), klasa (1-9), dhe tipi i klasës....",""],
["./classeslist.html","AdminForm &#62; ClassesList","Në këtë pjesë shfaqet lista e klasëve me të dhënat përkatëse:",""],
["./commentcreate.html","TeacherForm &#62; CommentCreate","Për të krijuar një vërejtje të re, hapet forma:  ku shtypen të dhënat: zgjedhet klasa, lënda, ora mësimore (1-6), dhe përmbajtja e vërejtjes....",""],
["./commentlist.html","TeacherForm &#62; CommentList","Në këtë pjesë shfaqet lista e vërejtjeve me të dhënat përkatëse:",""],
["./directormenu.html","DirectorMenu","Pasi të jepën të dhënat (username dhe password) dhe së zgjedhet gjuha (në këtë rast inglisht) hapet)Menu e Administrstës, nëse përdoruesi ka roli ...",""],
["./introduction.html","Introduction","– Sistemi për Shkollën Fillore është një sistem për përdorim nga administrata, arsimtarët, dhe drejtori.",""],
["./login.html","Login","Pasi të hapet aplikacioni \"MenaxhimiDitarit\", hapet forma për qasjen në aplikacion, si në vijim:",""],
["./review.html","DirectorMenu &#62; Review","Në këtë pjesë shfaqet lista e vërejtjeve që duhet të shqyrtohen (apo edhe të shqyrtuara) me të dhënat përkatëse:",""],
["./reviewcomment.html","DirectorMenu &#62; ReviewComment","Për të shqyrtuar një vërejtje, hapet forma:  ku shqyrtohet vërejtja. Pjesa  tregon se të dhënat që i shtypni në rubrikën e caktuar, ësht...",""],
["./rolelist.html","DirectorMenu &#62; RoleList","Në këtë pjesë shfaqet lista e roleve të aplikacionit:",""],
["./roomcreate.html","AdminForm &#62; RoomCreate","Për të krijuar një sallë të re, haëët forma:  ku shtypen të dhënat: numri i sallës dhe tipi i sallës. Pjesa  tregon se,të dhëeat që i sh...",""],
["./roomlist.html","AdminForm &#62; RoomList","Në këtë pjesë shfaqet lista e sallave me të dhënat përkatëse:",""],
["./schedulecreate.html","AdminForm &#62; ScheduleCreate","Për të krijuar një orarë të re, hapet forma:   ku shtypen të dhënat: zgjedhet klasa, lënda, ora mësimore (1-6), dhe dita javore (e hënë - e p...",""],
["./schedulelist.html","AdminForm &#62; ScheduleList","Në këtë pjesë shfaqet lista e orarit me të dhënat përkatëse:",""],
["./staffabsencecreate.html","DirectorMenu &#62; StaffAbsenceCreate","Për të krijuar një mungesë të stafit të ri, hapet forma:",""],
["./staffabsencelist.html","DirectorMenu &#62; StaffAbsenceList","Në këtë pjesë shfaqet lista e mungesave të stafit me të dhënat përkatëse:",""],
["./subjectcreate.html","AdminForm &#62; SubjectCreate","Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam velit risus, placerat et, rutrum nec, condimentum at, leo. Aliquam in augue a ma...",""],
["./subjectlist.html","AdminForm &#62; SubjectList","Në këtë pjesë shfaqet lista e lëndëve me të dhënat përkatëse:",""],
["./teacherform.html","TeacherForm","Pasi të jepën të dhënat (username dhe password) dhe të zgjedhet gjuha (në këtë rast anglisht) hapet Menu e Administratës, nëse përdoruesi ka rolin...",""],
["./teacherlist_director.html","DirectorMenu &#62; TeacherList_Director","Në këtë pjesë shfaqet lista e arsimtarëve me të dhënat e tij:",""],
["./teacherscreate.html","AdminForm &#62; TeachersCreate","Për të kri uar një arsimtarë hë ri, hapet forma:  ku shtypen të dhënat: emri(nuk pranohet numri apo ndonjë simbol), mbiemri(nuk pranohet numr...",""],
["./teacherslist.html","AdminForm &#62; TeachersList","Në këtë pjasë shfaqet lista e arsimtarëvepse të dhënat e tij:",""],
["./topiccreate.html","TeacherForm &#62; TopicCreate","Për të krijuar një temë të re, hapet forma:  ku shtypen të dhënat: zgjedhet klasa, lënda, ora mësimore (1-6), dhe shkruhet përmbajtja e temës...",""],
["./topiclist.html","TeacherForm &#62; TopicList","Në këtë pjesë shfaqet lista e temave me të dhënat përkatëse:",""],
["./userchangepassword.html","DirectorMenu &#62; UserChangePassword","Për të përditësuar fjalëkalimin e një përdorues, hapet forma:",""],
["./usercreate.html","DirectorMenu &#62; UserCreate","Për të krijuar një përdorues të ri, hapet forma:  ku shtypen të dhënat: zgjedhet roli dhe nëse roli i përdoruesit është Administrator apo Dir...",""],
["./userlist.html","DirectorMenu &#62; UserList","Në këtë pjesë shfaqet lista e përdoruesve të aplikapienet me të dhënat përkatëse:",""],
["./userupdate.html","DirectorMenu &#62; UserUpdate","Për të përdiëësuar një pëadorues, hapet forma:  ku shtnpen të dhënat: zgeedhet roli dhe nnse roli i përdoruesit është Administrator apo Direc...",""]];
